# Generated by Django 5.2.5 on 2025-08-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device',
            field=models.OneToOneField(blank=True, help_text='綁定的樹梅派設備，如有', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pi_devices.device'),
        ),
    ]
