# Generated by Django 5.2.5 on 2025-08-12 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0006_alter_device_last_ping_alter_device_serial_number_and_more'),
        ('users', '0002_user_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.OneToOneField(blank=True, help_text='綁定的樹梅派設備，如有（用於判斷線上狀態）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pi_devices.device'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='邀請此使用者的人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], default='user', help_text='使用者在系統中的角色層級', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
