# Generated by Django 5.2.5 on 2025-08-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device',
        ),
    ]
