# Generated by Django 5.2.5 on 2025-08-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_devicesharerequest_groupsharegrant'),
        ('users', '0004_remove_user_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_groups',
            field=models.ManyToManyField(blank=True, related_name='users', through='groups.GroupMembership', to='groups.group'),
        ),
    ]
