name: HomePiWeb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - psycopg2
  - sqlite
  - tk
  - openssl
  - ca-certificates
  - setuptools
  - wheel
  - tzdata
  - zlib
  - bzip2
  - xz
  - pip:
      - asgiref==3.9.1
      - certifi==2025.8.3
      - channels==4.3.1
      - channels-redis==4.3.0
      - charset-normalizer==3.4.3
      - django==5.2.5
      - djangorestframework==3.16.1
      - dnspython==2.8.0
      - gunicorn==23.0.0
      - idna==3.10
      - msgpack==1.1.1
      - packaging==25.0
      - pillow==11.3.0
      - psycopg2-binary==2.9.10
      - pymongo==4.14.1
      - python-dotenv==1.1.1
      - qrcode==8.2
      - redis==6.4.0
      - requests==2.32.4
      - sqlparse==0.5.3
      - urllib3==2.5.0
      - whitenoise==6.9.0
