name: HomePiWeb
channels:
  - defaults
dependencies:
  - python=3.11.13
  - pip
  - pip:
      - asgiref==3.9.1
      - django==5.2.5
      - pillow==11.3.0
      - qrcode==8.2
      - sqlparse==0.5.3
