"""
Django settings for HomePiWeb project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = (
    Path(__file__).resolve().parent.parent
)  # 是用來「定位專案最頂層目錄」的路徑變數名稱


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@1cytfof3ry-@pl+#-t@sqconfp)ec87&a($qn9l-lo#*e^8@%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 上線改 False

ALLOWED_HOSTS = ["*"]  # 開發時使用

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8800",
    "http://127.0.0.1:8800",
    "http://192.168.67.42:8800",
    "http://192.168.0.100:8800",
    "http://172.28.232.36:8800",
]

AUTH_USER_MODEL = "users.User"  # 自訂 User 模型是在 users app 內，叫 User 這個 class

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "pi_devices",
    "groups",
    "invites",
    "notifications",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "HomePiWeb.middleware.RequireGroupMiddleware",
]

ROOT_URLCONF = "HomePiWeb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HomePiWeb.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,  # 預設 5 秒，太短了
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hant"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "media/"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/home/"  # 登入成功後導向
LOGOUT_REDIRECT_URL = "/login/"  # 登出後導向（可選）

# 忘記密碼：是否寄信（False=頁面顯示重設連結，True=寄信）
PASSWORD_RESET_SEND_EMAIL = False
# 寄信基礎設定（先留著，未來開啟就能用）
DEFAULT_FROM_EMAIL = "no-reply@example.com"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # 先用 console


# 是否允許「一般成員」將自己的裝置掛入群組（預設 False）
GROUP_ALLOW_MEMBER_ATTACH = False

TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "notifications.context_processors.notifications_summary",
]

# 裝置線上視窗（你 ping 已使用）
DEVICE_ONLINE_WINDOW_SECONDS = 60

# 長輪詢單次等待上限（秒）
DEVICE_COMMAND_MAX_WAIT_SECONDS = 20

# 指令有效期（秒）
DEVICE_COMMAND_EXPIRES_SECONDS = 30

# 你現在是 HTTP，不要開 Secure cookie
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False

LOGIN_EXEMPT_URLS = [
    r"^hls/.*$",  # ← HLS 代理整條放行
    r"^device_ping/?$",  # ← Pi 心跳
    r"^device_pull/?$",  # ← Pi 拉指令
    r"^device_ack/?$",  # ← Pi 回報執行結果
]

SECURE_CROSS_ORIGIN_OPENER_POLICY = None
