# Generated by Django 5.2.5 on 2025-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='設備出廠序號，作為裝置的唯一識別', max_length=100, unique=True)),
                ('verification_code', models.CharField(help_text='用戶掃描 QRCode 後，需輸入的驗證碼', max_length=20)),
                ('is_bound', models.BooleanField(default=False, help_text='是否已綁定為 SuperAdmin，綁定後不可再次註冊')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='裝置在系統中建立的時間')),
            ],
        ),
    ]
