# Generated by Django 5.2.5 on 2025-08-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(editable=False, help_text='設備出廠序號，作為裝置的唯一識別', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='verification_code',
            field=models.CharField(editable=False, help_text='用戶掃描 QRCode 後，需輸入的驗證碼', max_length=20),
        ),
    ]
