# Generated by Django 5.2.5 on 2025-08-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0002_alter_device_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, help_text='註冊連結專用 Token', max_length=64, null=True, unique=True),
        ),
    ]
