# Generated by Django 5.2.5 on 2025-08-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0003_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='綁定裝置的內網 IP', null=True),
        ),
    ]
