# Generated by Django 5.2.5 on 2025-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0004_device_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
