# Generated by Django 5.2.5 on 2025-08-08 05:49

import django.core.validators
import pi_devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0005_device_last_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_ping',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default=pi_devices.models.gen_serial_number, editable=False, help_text='設備出廠序號，作為裝置的唯一識別', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^PI-[A-Z0-9]{8}$', '序號格式須為 PI-XXXXXXXX')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, default=pi_devices.models.gen_token, help_text='註冊連結專用 Token', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='verification_code',
            field=models.CharField(default=pi_devices.models.gen_verification_code, editable=False, help_text='用戶掃描 QRCode 後，需輸入的驗證碼', max_length=20),
        ),
    ]
