# Generated by Django 5.2.5 on 2025-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0006_alter_device_last_ping_alter_device_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='display_name',
            field=models.CharField(blank=True, help_text='自訂裝置顯示名稱；若留空則顯示序號', max_length=100),
        ),
    ]
