# Generated by Django 5.2.5 on 2025-08-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0007_device_display_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_bound'], name='pi_devices__is_boun_b19489_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_ping'], name='pi_devices__last_pi_332385_idx'),
        ),
    ]
