# Generated by Django 5.2.5 on 2025-08-13 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0008_device_pi_devices__is_boun_b19489_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, help_text='裝置擁有者（綁定後）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_bound',
            field=models.BooleanField(default=False, help_text='是否已被某位使用者綁定'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user'], name='pi_devices__user_id_882d05_idx'),
        ),
    ]
