# Generated by Django 5.2.5 on 2025-08-18 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0009_device_user_alter_device_is_bound_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('req_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('taken', 'taken'), ('done', 'done'), ('failed', 'failed'), ('expired', 'expired')], db_index=True, default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='pi_devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'status'], name='pi_devices__device__046915_idx'), models.Index(fields=['req_id'], name='pi_devices__req_id_024595_idx')],
            },
        ),
    ]
