# Generated by Django 5.2.5 on 2025-08-20 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0010_devicecommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('light', '燈光'), ('fan', '風扇/空調')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='pi_devices.device')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('device', 'slug')},
            },
        ),
    ]
