# Generated by Django 5.2.5 on 2025-08-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0012_auto_20250820_1319'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicecapability',
            index=models.Index(fields=['device', 'kind'], name='pi_devices__device__eab7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecapability',
            index=models.Index(fields=['device', 'enabled'], name='pi_devices__device__063ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['device', 'created_at'], name='pi_devices__device__a94b27_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicecommand',
            constraint=models.UniqueConstraint(fields=('device', 'req_id'), name='uniq_req_per_device'),
        ),
    ]
