# Generated by Django 5.2.5 on 2025-08-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0013_devicecapability_pi_devices__device__eab7cc_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devicecapability',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='devicecapability',
            constraint=models.UniqueConstraint(fields=('device', 'slug'), name='uniq_cap_slug_per_device'),
        ),
    ]
