# Generated by Django 5.2.5 on 2025-08-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0014_alter_devicecapability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_streaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='last_hls_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
