# Generated by Django 5.2.5 on 2025-09-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0015_device_is_streaming_device_last_hls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecapability',
            name='cached_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
