# Generated by Django 5.2.5 on 2025-09-03 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0016_devicecapability_cached_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('canceled', 'canceled'), ('failed', 'failed')], db_index=True, default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pi_devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'status', 'run_at'], name='pi_devices__device__783f8a_idx')],
            },
        ),
    ]
