# Generated by Django 5.2.5 on 2025-09-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_devices', '0017_deviceschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecapability',
            name='kind',
            field=models.CharField(choices=[('light', '燈光'), ('fan', '風扇/空調'), ('locker', '電子鎖')], max_length=20),
        ),
    ]
