# Generated by Django 5.2.5 on 2025-08-13 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('pi_devices', '0009_device_user_alter_device_is_bound_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已拒絕')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_requests', to='pi_devices.device')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_share_requests', to='groups.group')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_share_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_share_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'status'], name='groups_devi_group_i_1da894_idx'), models.Index(fields=['requester', 'status'], name='groups_devi_request_cc0955_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'group', 'device'), name='uniq_pending_device_share_request')],
            },
        ),
        migrations.CreateModel(
            name='GroupShareGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_share_grants', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_grants', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_share_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'is_active'], name='groups_grou_group_i_b7c120_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'group'), name='uniq_active_group_share_grant')],
            },
        ),
    ]
