# Generated by Django 5.2.5 on 2025-08-22 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupdevicepermission'),
        ('pi_devices', '0014_alter_devicecapability_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdevicepermission',
            name='created_at',
        ),
        migrations.AddField(
            model_name='groupdevicepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupdevicepermission',
            name='can_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='groupdevicepermission',
            index=models.Index(fields=['group', 'user'], name='groups_grou_group_i_854993_idx'),
        ),
        migrations.AddIndex(
            model_name='groupdevicepermission',
            index=models.Index(fields=['group', 'device'], name='groups_grou_group_i_5d64ba_idx'),
        ),
    ]
