# Generated by Django 5.2.5 on 2025-09-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_groupdevicepermission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicesharerequest',
            options={'verbose_name': '裝置分享申請', 'verbose_name_plural': '裝置分享申請'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '群組', 'verbose_name_plural': '群組'},
        ),
        migrations.AlterModelOptions(
            name='groupdevice',
            options={'verbose_name': '群組裝置關聯', 'verbose_name_plural': '群組裝置關聯'},
        ),
        migrations.AlterModelOptions(
            name='groupdevicepermission',
            options={'verbose_name': '群組裝置權限', 'verbose_name_plural': '群組裝置權限'},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'verbose_name': '群組成員', 'verbose_name_plural': '群組成員'},
        ),
        migrations.AlterModelOptions(
            name='groupsharegrant',
            options={'verbose_name': '群組分享權限', 'verbose_name_plural': '群組分享權限'},
        ),
    ]
