# Generated by Django 5.2.5 on 2025-08-21 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupdevicepermission'),
        ('invites', '0001_initial'),
        ('pi_devices', '0014_alter_devicecapability_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='used_count',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pi_devices.device'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='max_uses',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='InvitationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_control', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_devices.device')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_items', to='invites.invitation')),
            ],
            options={
                'unique_together': {('invitation', 'device')},
            },
        ),
    ]
