# Generated by Django 5.2.5 on 2025-08-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_remove_invitation_used_count_alter_invitation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
