# Generated by Django 5.2.5 on 2025-08-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_alter_invitation_code'),
        ('pi_devices', '0014_alter_devicecapability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitationdevice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invitation',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pi_devices.device'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddConstraint(
            model_name='invitationdevice',
            constraint=models.UniqueConstraint(fields=('invitation', 'device'), name='uniq_invitation_device'),
        ),
    ]
