# Generated by Django 5.2.5 on 2025-08-17 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('groups', '0002_devicesharerequest_groupsharegrant'),
        ('notifications', '0001_initial'),
        ('pi_devices', '0009_device_user_alter_device_is_bound_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedup_key', ''), _negated=True), fields=('user', 'dedup_key'), name='uniq_user_dedupkey_when_present'),
        ),
    ]
