# Generated by Django 5.2.5 on 2025-08-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_uniq_user_dedupkey_when_present'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
    ]
